# plugins
dependencyManagement=1.1.7
johnrengelman=8.1.1
spotless=7.0.0
sonarlint=4.3.4
apacheJMeter=5.6.3
jmh=0.7.3

#depencencies
apectjweaver=1.9.19
assertj=3.26.3
awaitility=4.2.0
caffeine=3.1.8
expressly=5.0.0
feignMicrometer=13.6
glassfishExpressly=5.0.0
guava=33.0.0-jre
h2database=2.2.224
hibernateValidator=8.0.1.Final
jakartaEl=3.0.3
junit=5.11.4
liquibaseCore=4.33.0
logback=1.5.12
lombok=1.18.38
mapstruct=1.6.3
micrometer=1.12.0
mockito=5.15.2
postgres=42.6.0
projectlombok=1.18.30
resilience4j=2.1.0
springBootDependencies=3.2.0
springCloudCircuitbreaker=3.3.0
springCloudGateway=4.3.0
springdoc=2.8.5
springframework=6.2.7
springboot=3.5.4
# bom
springBoot=3.5.4
springBootCloud=2025.0.0
testcontainers=1.21.3

