###
POST http://localhost:8088/api/agent
Content-Type: application/json

{
  "id" : "",
  "login" :  "aaa",
  "password" : "123"
}

###
POST http://localhost:8088/api/agent
Content-Type: application/json

{
  "id" : "",
  "login" :  "bbb",
  "password" : "123"
}
### GET request to example server
GET http://localhost:8088/api/agent

###
### GET request to example server
GET http://localhost:8088/api/agent?name=aaa

###
GET http://localhost/hello
Content-Type: text/plain

